package com.riders.thelab.core.ui.compose.color

import androidx.compose.ui.graphics.Color

/**
 * Linked to RedTheme file
 */
val md_red_theme_light_primary = Color(0xFF904A42)
val md_red_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_red_theme_light_primaryContainer = Color(0xFFFFDAD5)
val md_red_theme_light_onPrimaryContainer = Color(0xFF3B0906)
val md_red_theme_light_secondary = Color(0xFF775652)
val md_red_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_red_theme_light_secondaryContainer = Color(0xFFFFDAD5)
val md_red_theme_light_onSecondaryContainer = Color(0xFF2C1512)
val md_red_theme_light_tertiary = Color(0xFF705C2E)
val md_red_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_red_theme_light_tertiaryContainer = Color(0xFFFCDFA6)
val md_red_theme_light_onTertiaryContainer = Color(0xFF261A00)
val md_red_theme_light_error = Color(0xFFBA1A1A)
val md_red_theme_light_onError = Color(0xFFFFFFFF)
val md_red_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_red_theme_light_onErrorContainer = Color(0xFF410002)
val md_red_theme_light_background = Color(0xFFFFF8F7)
val md_red_theme_light_onBackground = Color(0xFF231918)
val md_red_theme_light_surface = Color(0xFFFFF8F7)
val md_red_theme_light_onSurface = Color(0xFF231918)
val md_red_theme_light_surfaceVariant = Color(0xFFF5DDDA)
val md_red_theme_light_onSurfaceVariant = Color(0xFF534341)
val md_red_theme_light_outline = Color(0xFF857370)
val md_red_theme_light_outlineVariant = Color(0xFFD8C2BE)
val md_red_theme_light_scrim = Color(0xFF000000)
val md_red_theme_light_inverseSurface = Color(0xFF392E2C)
val md_red_theme_light_inverseOnSurface = Color(0xFFFFEDEA)
val md_red_theme_light_inversePrimary = Color(0xFFFFB4AA)
val md_red_theme_light_surfaceDim = Color(0xFFE8D6D3)
val md_red_theme_light_surfaceBright = Color(0xFFFFF8F7)
val md_red_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_red_theme_light_surfaceContainerLow = Color(0xFFFFF0EE)
val md_red_theme_light_surfaceContainer = Color(0xFFFCEAE7)
val md_red_theme_light_surfaceContainerHigh = Color(0xFFF7E4E1)
val md_red_theme_light_surfaceContainerHighest = Color(0xFFF1DEDC)

val md_red_theme_dark_primary = Color(0xFFFFB4AA)
val md_red_theme_dark_onPrimary = Color(0xFF561E18)
val md_red_theme_dark_primaryContainer = Color(0xFF73342C)
val md_red_theme_dark_onPrimaryContainer = Color(0xFFFFDAD5)
val md_red_theme_dark_secondary = Color(0xFFE7BDB7)
val md_red_theme_dark_onSecondary = Color(0xFF442926)
val md_red_theme_dark_secondaryContainer = Color(0xFF5D3F3B)
val md_red_theme_dark_onSecondaryContainer = Color(0xFFFFDAD5)
val md_red_theme_dark_tertiary = Color(0xFFDFC38C)
val md_red_theme_dark_onTertiary = Color(0xFF3E2E04)
val md_red_theme_dark_tertiaryContainer = Color(0xFF574419)
val md_red_theme_dark_onTertiaryContainer = Color(0xFFFCDFA6)
val md_red_theme_dark_error = Color(0xFFFFB4AB)
val md_red_theme_dark_onError = Color(0xFF690005)
val md_red_theme_dark_errorContainer = Color(0xFF93000A)
val md_red_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_red_theme_dark_background = Color(0xFF1A1110)
val md_red_theme_dark_onBackground = Color(0xFFF1DEDC)
val md_red_theme_dark_surface = Color(0xFF1A1110)
val md_red_theme_dark_onSurface = Color(0xFFF1DEDC)
val md_red_theme_dark_surfaceVariant = Color(0xFF534341)
val md_red_theme_dark_onSurfaceVariant = Color(0xFFD8C2BE)
val md_red_theme_dark_outline = Color(0xFFA08C89)
val md_red_theme_dark_outlineVariant = Color(0xFF534341)
val md_red_theme_dark_scrim = Color(0xFF000000)
val md_red_theme_dark_inverseSurface = Color(0xFFF1DEDC)
val md_red_theme_dark_inverseOnSurface = Color(0xFF392E2C)
val md_red_theme_dark_inversePrimary = Color(0xFF904A42)
val md_red_theme_dark_surfaceDim = Color(0xFF1A1110)
val md_red_theme_dark_surfaceBright = Color(0xFF423735)
val md_red_theme_dark_surfaceContainerLowest = Color(0xFF140C0B)
val md_red_theme_dark_surfaceContainerLow = Color(0xFF231918)
val md_red_theme_dark_surfaceContainer = Color(0xFF271D1C)
val md_red_theme_dark_surfaceContainerHigh = Color(0xFF322826)
val md_red_theme_dark_surfaceContainerHighest = Color(0xFF3D3231)